### ISSUE TITLE
Not open wallet . Ledger Nano S

### ISSUE THREAD

**Issue by lluiggi** [tronscan/tronscan-desktop#34] opened 2018-09-27 08:40 UTC
I get message "No open wallet to view" even if I have already unlock my Ledger and opened Tron app 0.0.2. I can see my address, but not open the wallet.
Is the first time it appens
until now everything worked fine
any suggestion ?

**Comment by polaks** [comment] 2018-09-27 08:57
> I get message "No open wallet to view" even if I have already unlock my Ledger and opened Tron app 0.0.2. I can see my address, but not open the wallet.
> Is the first time it appens
> until now everything worked fine
> any suggestion ?

We have the same problem

**Comment by ishafizan** [comment] 2018-10-11 13:54
facing same issue with ledger nano s, tronscan app on mac osx
- ledger connected
- clicked 'open wallet'
- getting 'no open wallet  to view'

**Comment by Aube0524** [comment] 2018-10-11 14:16
Same with me

**Comment by Aube0524** [comment] 2018-10-11 15:32
used it for the past months with no issues first time today

**Comment by OliverReex** [comment] 2018-10-11 16:02
the same problem

**Comment by chrisc9418** [comment] 2018-10-11 16:10
Exact same issue here - "no open wallet to view"  I've verified that my trx is there at the proper address vis tronscan explorer but can't access it

**Comment by Brianstrip** [comment] 2018-10-14 01:33
Same problem here guys....anyone got any ideas?

**Comment by wuno** [comment] 2018-12-03 13:33
This issue seems to be happening again. 

> No open wallet to view

At first I figured it was just the APIs being updated again when it started last night so I waited till this morning to check again. I still have the issue for going on 12 hours. 

Does anyone have any information on this issue as I still can not access my wallet through Tronscan desktop. 

Thanks,

**Comment by finehobby** [comment] 2018-12-07 10:43
the problem still persists. Tronscan desktop wallet doesnt work with ledger nano. You can take the Tronwatch.exe but then you can not use DEX and you can not trade the received SEED to TRX.
Please help

**Comment by Inmate64** [comment] 2018-12-19 19:47
No open wallet to view. This is all I get, and have been getting for a while. Worked fine before. Any clue what to do? Service@tron not helping so I thought I'd try here.

**Comment by finehobby** [comment] 2018-12-19 20:35
hello, you can use  https://tronscan.github.io/tronscan-frontend/# 
but without trading, trading doesnt work in this version,
nobody helps here from TRON, very bad and not professional

**Comment by lluiggi** [comment] 2018-12-19 22:34
hello, you can use https://tronscan.github.io/tronscan-frontend/#

Missatge de Inmate64 <notifications@github.com> del dia dc., 19 de des.
2018 a les 20:47:

**Comment by Inmate64** [comment] 2018-12-20 04:38
Thanks, but these just allow me to see but not get to the trx, or am I mistaken? As it is now, it's as if my trx are held hostage.

**Comment by Inmate64** [comment] 2018-12-21 02:13
Yeah... basically we need to get the word out about how they do things at Tron. This is criminal.

**Comment by Inmate64** [comment] 2018-12-21 03:30
It would have served me well to have received this from Tron service in the one email they sent. They asked a question, which I answered. 4 emails and a week later from me, nothing except your help here. I work in the service industry, and understand hard work with little praise. I also understand professional responsibility to those being served. I referred to a situation as criminal, not a person or group of people. I believe my frustration helped me word it in that manner. It has been a few months now, so my loss of faith in the process you explained was easily on display. Thanks for your attempt to help, as it is greatly appreciated.

**Comment by wuno** [comment] 2018-12-21 04:08
@Inmate64 Happy to help. I completely understand it can be frustrating. 

Here is a little heads up for you. If you find yourself in a jam and need help, join this Discord channel, 

https://discord.gg/hdJR3hY

This is the Discord channel for Developers and Senior Reps. Surely someone will answer your questions in the future if you join.

**Comment by finehobby** [comment] 2018-12-21 09:07
@wuno:
thanks for the info, i accept that the developers work hard and i am grateful for it. But the point is that the system is missing. When a tool is developed, it should be always available. Otherwise it doesn't help and creates frustration.
I have my TRX on the ledger nano and therefore need the solution like a few weeks ago with tronscan desktop, that you can do everything safely and completely with one app: Access, overview, freeze, transfer, vote and trade. 
I hope you understand that everything else is unprofessional. The many tools are of no use, less with good quality would be more !!!

**Comment by Inmate64** [comment] 2018-12-22 15:15
Tron... still holding my trx hostage. I'm very angry. I believe they don't care. Justin is somewhere not caring about this situation. That's what I believe, until proven otherwise.

**Comment by wuno** [comment] 2018-12-22 15:16
@Inmate64 tell me what you are dealing with and let's see if we can figure out how to fix it.

**Comment by Inmate64** [comment] 2018-12-22 15:42
Access. That's the issue. I have TRX that I was able to access using ledger nano s, and Tronscan from my desktop. I have for weeks now not been able to access this wallet. It's not about doing anything with the TRX. It's about not being able to get to it. It's about access. It's also about seeing others with similar issues. I currently have TRX on an exchange. Why would I want to move it to a wallet in which I'm having issues? Also, and this is the real point, I couldn't even do so if I wanted.

**Comment by wuno** [comment] 2018-12-22 15:50
So are you saying when you go to this link, 

https://tronscan.github.io/tronscan-frontend/#/account

You can not connect your ledger using the Open_Ledger link under "Open Wallet" in the top right of the screen?

**Comment by Inmate64** [comment] 2018-12-22 18:59
Not at home, but working on trying that when I get in. Tried a few times in the past and it didn't work, but we'll give it another go.

**Comment by Lord-Highfixer** [comment] 2018-12-23 05:31
> Access. That's the issue. I have TRX that I was able to access using ledger nano s, and Tronscan from my desktop. I have for weeks now not been able to access this wallet. It's not about doing anything with the TRX. It's about not being able to get to it. It's about access. It's also about seeing others with similar issues. I currently have TRX on an exchange. Why would I want to move it to a wallet in which I'm having issues? Also, and this is the real point, I couldn't even do so if I wanted.

I TOTALLY panicked when I transferred my TRON to my Ledger 5 days ago and could not longer find them anywhere. Turns out I simply reversed my access accidentally making sure my I was logged into my Ledger first with TRON App selected, and I believe I still have "Browser Support" enabled, not sure if that makes a difference for the TRONSCAN app.

**Comment by wuno** [comment] 2018-12-23 05:35
Yes everyone has full access to their TRX using this link as stated before, 

https://tronscan.github.io/tronscan-frontend/#/account

What I do is sign into my ledger and open the Tron app, 
Then click on Open_Ledger at the link above. 
Then click the green button on the screen when it launches. 

At that point you can send your Tron or even vote for SRs if you want. 

This has been live for over a week now. We were only blocked from accessing our TRX for about 3 or 4 days till this app came on last week. 

If anyone else has problems let us know what the problem is and we can try to help you solve it.

**Comment by Lord-Highfixer** [comment] 2018-12-23 05:38
> @Inmate64 tell me what you are dealing with and let's see if we can figure out how to fix it.

Please make sure that someone updates the steps because the steps are swapped and like Inmate64, I couldn't access my TRON coin and I slept very little for 5 days and just now reconnected to my coins due to the steps. I believe the steps here on Github and the steps on Ledger website both said to open the TRON wallet, then go to the device, log in, and access it via Wallet > Open > Ledger. Instead I opened my Ledger, typed my PIN, Opened my TRON App on my Ledger, THEN...I opened TRONSCAN, opened wallet, selected Ledger and it worked finally.

**Comment by wuno** [comment] 2018-12-23 07:01
@Lord-Highfixer Where do you see steps written somewhere on the internet that were wrong? 

I personally did not see any steps anywhere, I think for most of us we just figured it out. 

Would you mind posting the link?

**Comment by finehobby** [comment] 2018-12-23 09:17
Hello, I tried it again, but ist does not work, no matter in which order of succession i open ledger and desktop app, issue not fixed  ....................

**Comment by Lord-Highfixer** [comment] 2018-12-23 14:18
> @Lord-Highfixer Where do you see steps written somewhere on the internet that were wrong?
> 
> I personally did not see any steps anywhere, I think for most of us we just figured it out.
> 
> Would you mind posting the link?

The steps at Ledger.com is one, and others I believe was Reddit and other places I searched when the steps from Ledger did not get me access to my Ledger:
https://support.ledger.com/hc/en-us/articles/360006904193-Tron-TRX-

There it states:

1.  Download and install the latest Tronscan Desktop release.
2.     Open Tronscan Desktop.
3.     Click on open wallet at the top right corner and again open wallet.
4.     Select Ledger. Tronscan will display Ledger connected.
5.     Click on open wallet and you will be automatically redirected to your Tron wallet.

However, for my situation:

1. Connect Ledger to PC
2. Enter PIN
3. Open TRON app (not sure if I needed to Enable Browsing but it is)
4. Open Tronscan with Ledger support
5. Open Wallet
6. Connect to Ledger
and I finally can use my Ledger with TRON. 

If you follow the previous instructions at Ledger, and did a new install of the TRON app, you may have already connected the Ledger and opened the app. For those who have already installed the TRON app and skip "Install the TRON app", then the "Setup Tronscan Desktop" does not give the directions to make a connection. 

...the easier we make these steps to follow in an exact order from any point of contact the faster the world will be more comfortable with TRON. The problem is that not everyone may be installing the TRON App, Tronscan and attempting a transaction all at once. In these situations, the apps are already installed and often running, then connecting the Ledger after the app is running does not work in my situation. So the steps should explain different scenarios "if the app is already installed".  Install app, Install Tronscan, connecting Ledger, reconnecting Ledger after Installation of TRON app, reconnection after Tronscan Desktop install, etc.

**Comment by wuno** [comment] 2018-12-23 17:56
@finehobby You are not supposed to be using the Desktop App. The app no longer works from your desktop. You have to actually go to this link instead, 

https://tronscan.github.io/tronscan-frontend/#/account

**Comment by wuno** [comment] 2018-12-23 18:33
This is the Tweet from the developer who released the new version of Tronscan to allow people with a Ledger to access their wallet, 

https://twitter.com/Razko/status/1069970039070064640

This is not a Tron Foundation developer from what I can see. I suggest people still confused about this to take a look at the tweet. 

> A work-in-progress version is ready at https://tronscan.github.io/tronscan-frontend …. Click on "open wallet" on the top right and then Ledger. Only chrome is supported for now and only voting, freezing and sending have been implemented. Will finish the rest of the features in the next few days.
> 
> 9:01 AM - 4 Dec 2018

**Comment by finehobby** [comment] 2018-12-23 19:09
@wuno:
I don't think you want to understand me. 
I have already written everything above.

Once more: 
1.) When a tool is developed, it should be always available. The Tronscan desktop App with ledger nano was working perfect, why no more?
Useres hold TRX on the ledger nano and therefore need the solution like a few weeks ago with tronscan desktop, that you can do everything safely and completely with one app: Access, overview, freeze, transfer, vote and trade.
2.) The work-in-progress Version of the WEB-frontend with ledger nano as mentioned above, is not complete and you can not trade !! Thats the problem.

That means, I can use the  https://tronscan.github.io/tronscan-frontend for freeze or voting, but when I want to trade SEED/TRX or TREC/TRX and so on, I have to transfer the Token to an other wallet, then there trade und transfer back. Thats cumbersome and not really a solution

**Closed** 2019-02-15 07:30 UTC

**Comment by Xirpple** [comment] 2019-02-20 19:14
I just spent two hours trying to access my TRX from Tronscan desktop, while getting the same no open wallet message.  I finally gained access through Tronscan.org website on Google Chrome.  It did not work on Tronscan.github or on Firefox.  I transferred tokens right out and to a different wallet.

**Comment by touseefbuchh** [comment] 2019-04-05 18:39
i am facing the same issue since morning today. Can anyone help by suggesting what shud i do to log into my TRON wallet. Have tried tronscan site and may other options but all in vain.... Plz help !!

**Comment by Xirpple** [comment] 2019-04-05 18:48
I was able to get my Tron buy logging into Ttonscan website using Chrome.    It did not work through the Tronscan program or Firefox.
  

  
  

  
  
>

**Comment by Lord-Highfixer** [comment] 2019-06-05 06:29
"No Open Wallet to View" - Fixed 
Both Chromium (Brave and Chrome) work and my TRONSCAN works again

My TRONSCAN app and the Chromium (Chrome and Brave) each fail allowing me access to my TRX with my Ledger Nano S. The Ledger tab and the web browsers each tell me "No Open Wallet to View". I clicked "Open Wallet" it brought me to a page that said "No Open Wallet to View".

I tried updating my Ledger Liver app and TronScan and tried different browsers. I started to wonder if I downloaded a Trojaned version and some Red Army Krypto Nazi bamboozled me...

But no, this time it's not the commies or the Nazis, not yet anyway. The fix is simple, remove TRON app from your Ledger Nano and reinstall. You will not lose your crypto, the key is the same. When you load one of the TRON apps and connect to your Ledger Nano, you will see your wallet and can copy it in case you are paranoid as I am.

You can uninstall Apps from your Ledger and reinstall them, you don't lose your crypto and you regain access to your crypto. In case some of you do not know, when you have too many crypto versions for your Nano you can uninstall the app and install a new crypto app to sync up your coins. You can swap your apps as you need because some apps are larger than others leaving less room on your Nano for other cryptos.

**Comment by Lord-Highfixer** [comment] 2019-06-05 06:32
> i am facing the same issue since morning today. Can anyone help by suggesting what shud i do to log into my TRON wallet. Have tried tronscan site and may other options but all in vain.... Plz help !!

You should be able to fix it by uninstalling the TRON TRX app on your Ledger Nano via Ledger Live app. Connect your device with Ledger Live, uninstall, immediately reinstall. It fixed my access problems using both the browsers and my TRONSCAN app.
